//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinEcomDomain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VinEcom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VinEcom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VinEcomDomain.Resources.VinEcom", typeof(VinEcom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm vào giỏ hàng. Vui lòng thử lại..
        /// </summary>
        public static string VINECOM_ORDER_ADDTOCART_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_ADDTOCART_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã huỷ.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_DONE {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chuẩn bị.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_PREPARING {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao.
        /// </summary>
        public static string VINECOM_ORDER_STATUS_SHIPPING {
            get {
                return ResourceManager.GetString("VINECOM_ORDER_STATUS_SHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thức uống.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_BEVERAGE {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_BEVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món ăn.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_FOOD {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhu yếu phẩm.
        /// </summary>
        public static string VINECOM_PRODUCT_CATEGORY_NECESSITY {
            get {
                return ResourceManager.GetString("VINECOM_PRODUCT_CATEGORY_NECESSITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán cafe.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_BEVERAGE {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_BEVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quán ăn.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_FOOD {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạp hoá.
        /// </summary>
        public static string VINECOM_STORE_CATEGORY_GROCERY {
            get {
                return ResourceManager.GetString("VINECOM_STORE_CATEGORY_GROCERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại hoặc mật khẩu không chính xác..
        /// </summary>
        public static string VINECOM_USER_AUTHORIZE_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_USER_AUTHORIZE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại. Lỗi hệ thống.
        /// </summary>
        public static string VINECOM_USER_REGISTER_INTERNAL_FAILED {
            get {
                return ResourceManager.GetString("VINECOM_USER_REGISTER_INTERNAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã được sử dụng..
        /// </summary>
        public static string VINECOM_USER_REGISTER_PHONE_DUPLICATED {
            get {
                return ResourceManager.GetString("VINECOM_USER_REGISTER_PHONE_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công..
        /// </summary>
        public static string VINECOM_USER_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("VINECOM_USER_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string VINECOM_USER_ROLE_CUSTOMER {
            get {
                return ResourceManager.GetString("VINECOM_USER_ROLE_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài xế.
        /// </summary>
        public static string VINECOM_USER_ROLE_SHIPPER {
            get {
                return ResourceManager.GetString("VINECOM_USER_ROLE_SHIPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên cửa hàng.
        /// </summary>
        public static string VINECOM_USER_ROLE_STORESTAFF {
            get {
                return ResourceManager.GetString("VINECOM_USER_ROLE_STORESTAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe máy.
        /// </summary>
        public static string VINECOM_VEHICLE_TYPE_MOTORBIKE {
            get {
                return ResourceManager.GetString("VINECOM_VEHICLE_TYPE_MOTORBIKE", resourceCulture);
            }
        }
    }
}
